name = "ManiFactor"
uuid = "644c2d91-53c3-4334-b351-920c96c0b266"
authors = ["Simon Jacobsson <simon.jacobsson@kuleuven.be>"]
version = "0.1.1"

[deps]
ApproximatingMapsBetweenLinearSpaces = "31d768e5-ae28-4338-b319-fc9871ebca58"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"

[compat]
julia = "1"
ApproximatingMapsBetweenLinearSpaces = "0.1"
Kronecker = "0.5"
LinearAlgebra = "1"
Manifolds = "0.10.10 - 0.10"
ManifoldsBase = "0.15"
SplitApplyCombine = "1"
